import unittest
from sanskrit_transliteration import transliterate


class TestCases(unittest.TestCase):
    def test_hk_to_wx(self):
        self.assertEqual(
            transliterate(
                text="G",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "f"
        )
        self.assertEqual(
            transliterate(
                text="aGgaH",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "afgaH"
        )
        self.assertEqual(
            transliterate(
                text="jJAnam",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "jFAnam"
        )
        self.assertEqual(
            transliterate(
                text="RSiH",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "qRiH"
        )
        self.assertEqual(
            transliterate(
                text="|RSiH",
                from_scheme="HK",
                to_scheme="WX"
            ),
            ".qRiH"
        )
        self.assertEqual(
            transliterate(
                "rAmaH iva, 123|",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "rAmaH iva, 123."
        )
        self.assertEqual(
            transliterate(
                text="kaNThakam",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "kaNTakam"
        )
        self.assertEqual(
            transliterate(
                text="pArthAya pratibodhitAM bhagavatA nArAyaNena svayam vyAsena grathitAM purANamuninA madhye "
                     "mahAbhArate",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "pArWAya prawiboXiwAM BagavawA nArAyaNena svayam vyAsena graWiwAM purANamuninA maXye mahABArawe"
        )
        self.assertEqual(
            transliterate(
                text="DhuNDhikA'pi",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "DuNDikAZpi"
        )
        self.assertEqual(
            transliterate(
                "auau",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "OO"
        )
        self.assertEqual(
            transliterate(
                text="||auau||",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "..OO.."
        )
        self.assertEqual(
            transliterate(
                text="hara hara mahAdeva",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "hara hara mahAxeva"
        )
        self.assertEqual(
            transliterate(
                text="dugdha",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "xugXa"
        )
        self.assertEqual(
            transliterate(
                text="ataeva",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "awaeva"
        )
        self.assertEqual(
            transliterate(
                text="pitRRNAm kRte",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "piwQNAm kqwe"
        )
        self.assertEqual(
            transliterate(
                text="|.kRSNaM, vande| jagadgurum",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "..kqRNaM, vanxe. jagaxgurum"
        )
        self.assertEqual(
            transliterate(
                text="karNaH",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "karNaH"
        )
        self.assertEqual(
            transliterate(
                text="ahiMsA",
                from_scheme="HK",
                to_scheme="WX"
            ),
            "ahiMsA"
        )

    def test_wx_to_hk(self):
        self.assertEqual(
            transliterate(
                text="f",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "G"
        )
        self.assertEqual(
            transliterate(
                text="afgaH",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "aGgaH"
        )
        self.assertEqual(
            transliterate(
                text="jFAnam",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "jJAnam"
        )
        self.assertEqual(
            transliterate(
                text="qRiH",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "RSiH"
        )
        self.assertEqual(
            transliterate(
                text=".qRiH",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "|RSiH"
        )
        self.assertEqual(
            transliterate(
                text="rAmaH iva, 123.",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "rAmaH iva, 123|"
        )
        self.assertEqual(
            transliterate(
                text="pArWAya prawiboXiwAM BagavawA nArAyaNena svayam vyAsena graWiwAM purANamuninA maXye mahABArawe",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "pArthAya pratibodhitAM bhagavatA nArAyaNena svayam vyAsena grathitAM purANamuninA madhye mahAbhArate"
        )
        self.assertEqual(
            transliterate(
                text="DuNDikAZpi",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "DhuNDhikA'pi"
        )
        self.assertEqual(
            transliterate(
                text="kaNTakam",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "kaNThakam"
        )
        self.assertEqual(
            transliterate(
                text="OO",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "auau"
        )
        self.assertEqual(
            transliterate(
                text="karNaH",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "karNaH"
        )
        self.assertEqual(
            transliterate(
                text="xugXam",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "dugdham"
        )
        self.assertEqual(
            transliterate(
                text="..OO..",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "||auau||"
        )
        self.assertEqual(
            transliterate(
                text="hara hara mahAxeva",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "hara hara mahAdeva"
        )
        self.assertEqual(
            transliterate(
                text="awaeva",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "ataeva"
        )
        self.assertEqual(
            transliterate(
                text="piwQNAm kqwe",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "pitRRNAm kRte"
        )
        self.assertEqual(
            transliterate(
                text="..kqRNaM, vanxe. jagaxgurum",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "||kRSNaM, vande| jagadgurum"
        )
        self.assertEqual(
            transliterate(
                text="ahiMsA",
                from_scheme="WX",
                to_scheme="HK"
            ),
            "ahiMsA"
        )

    def test_slp1_to_hk(self):
        self.assertEqual(
            transliterate(
                text="N",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "G"
        )
        self.assertEqual(
            transliterate(
                text="aNgaH",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "aGgaH"
        )
        self.assertEqual(
            transliterate(
                text="jYAnam",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "jJAnam"
        )
        self.assertEqual(
            transliterate(
                text="rAmaH iva, 123.",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "rAmaH iva, 123|"
        )
        self.assertEqual(
            transliterate(
                text="kaRWakam",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "kaNThakam"
        )
        self.assertEqual(
            transliterate(
                text="pArTAya pratiboDitAM BagavatA nArAyaRena svayam vyAsena graTitAM purARamuninA maDye mahABArate",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "pArthAya pratibodhitAM bhagavatA nArAyaNena svayam vyAsena grathitAM purANamuninA madhye mahAbhArate"
        )
        self.assertEqual(
            transliterate(
                text="QuRQikA'pi",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "DhuNDhikA'pi"
        )
        self.assertEqual(
            transliterate(
                text="OO",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "auau"
        )
        self.assertEqual(
            transliterate(
                text="karRaH",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "karNaH"
        )
        self.assertEqual(
            transliterate(
                text="dugDam",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "dugdham"
        )
        self.assertEqual(
            transliterate(
                text="..OO..",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "||auau||"
        )
        self.assertEqual(
            transliterate(
                text="hara hara mahAdeva",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "hara hara mahAdeva"
        )
        self.assertEqual(
            transliterate(
                text="ataeva",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "ataeva"
        )
        self.assertEqual(
            transliterate(
                text="pitFRAm kfte",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "pitRRNAm kRte"
        )
        self.assertEqual(
            transliterate(
                text="..kfzRaM, vande. jagadgurum",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "||kRSNaM, vande| jagadgurum"
        )
        self.assertEqual(
            transliterate(
                text="ahiMsA",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "ahiMsA"
        )
        self.assertEqual(
            transliterate(
                text="fziH",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "RSiH"
        )
        self.assertEqual(
            transliterate(
                text=".fziH",
                from_scheme="SLP1",
                to_scheme="HK"
            ),
            "|RSiH"
        )

    def test_hk_to_slp1(self):
        self.assertEqual(
            transliterate(
                text="G",
                from_scheme="HK",
                to_scheme="SLP1",
            ),
            "N"
        )
        self.assertEqual(
            transliterate(
                text="aGgaH",
                from_scheme="HK",
                to_scheme="SLP1",
            ),
            "aNgaH"
        )
        self.assertEqual(
            transliterate(
                text="jJAnam",
                from_scheme="HK",
                to_scheme="SLP1",
            ),
            "jYAnam"
        )
        self.assertEqual(
            transliterate(
                text="rAmaH iva, 123|",
                from_scheme="HK",
                to_scheme="SLP1",
            ),
            "rAmaH iva, 123."
        )
        self.assertEqual(
            transliterate(
                text="pArthAya pratibodhitAM bhagavatA nArAyaNena svayam vyAsena grathitAM purANamuninA madhye mahAbhArate",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "pArTAya pratiboDitAM BagavatA nArAyaRena svayam vyAsena graTitAM purARamuninA maDye mahABArate"
        )
        self.assertEqual(
            transliterate(
                text="DhuNDhikA'pi",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "QuRQikA'pi"
        )
        self.assertEqual(
            transliterate(
                text="auau",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "OO"
        )
        self.assertEqual(
            transliterate(
                text="karNaH",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "karRaH"
        )
        self.assertEqual(
            transliterate(
                text="dugdham",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "dugDam"
        )
        self.assertEqual(
            transliterate(
                text="||auau||",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "..OO.."
        )
        self.assertEqual(
            transliterate(
                text="hara hara mahAdeva",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "hara hara mahAdeva"
        )
        self.assertEqual(
            transliterate(
                text="ataeva",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "ataeva"
        )
        self.assertEqual(
            transliterate(
                text="pitRRNAm kRte",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "pitFRAm kfte"
        )
        self.assertEqual(
            transliterate(
                text="kaNThakam",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "kaRWakam"
        )
        self.assertEqual(
            transliterate(
                text="||kRSNaM, vande| jagadgurum",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "..kfzRaM, vande. jagadgurum"
        )
        self.assertEqual(
            transliterate(
                text="ahiMsA",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "ahiMsA"
        )
        self.assertEqual(
            transliterate(
                text="RSiH",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            "fziH"
        )
        self.assertEqual(
            transliterate(
                text="|RSiH",
                from_scheme="HK",
                to_scheme="SLP1"
            ),
            ".fziH"
        )


if __name__ == '__main__':
    unittest.main()
